// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet() {
  return window['go']['backend']['App']['Greet']();
}

export function Multiply(arg1, arg2) {
  return window['go']['backend']['App']['Multiply'](arg1, arg2);
}
